// Comprehensive A to Z Countries Database with Official Flags & FIFA/ISO Codes

export const COUNTRIES = [
  { code: 'AFG', name: 'Afghanistan', flag: '🇦🇫' },
  { code: 'ALB', name: 'Albania', flag: '🇦🇱' },
  { code: 'ALG', name: 'Algeria', flag: '🇩🇿' },
  { code: 'AND', name: 'Andorra', flag: '🇦🇩' },
  { code: 'ANG', name: 'Angola', flag: '🇦🇴' },
  { code: 'ATG', name: 'Antigua and Barbuda', flag: '🇦🇬' },
  { code: 'ARG', name: 'Argentina', flag: '🇦🇷' },
  { code: 'ARM', name: 'Armenia', flag: '🇦🇲' },
  { code: 'AUS', name: 'Australia', flag: '🇦🇺' },
  { code: 'AUT', name: 'Austria', flag: '🇦🇹' },
  { code: 'AZE', name: 'Azerbaijan', flag: '🇦🇿' },
  { code: 'BAH', name: 'Bahamas', flag: '🇧🇸' },
  { code: 'BHR', name: 'Bahrain', flag: '🇧🇭' },
  { code: 'BAN', name: 'Bangladesh', flag: '🇧🇩' },
  { code: 'BRB', name: 'Barbados', flag: '🇧🇧' },
  { code: 'BLR', name: 'Belarus', flag: '🇧🇾' },
  { code: 'BEL', name: 'Belgium', flag: '🇧🇪' },
  { code: 'BLZ', name: 'Belize', flag: '🇧🇿' },
  { code: 'BEN', name: 'Benin', flag: '🇧🇯' },
  { code: 'BER', name: 'Bermuda', flag: '🇧🇲' },
  { code: 'BHU', name: 'Bhutan', flag: '🇧🇹' },
  { code: 'BOL', name: 'Bolivia', flag: '🇧🇴' },
  { code: 'BIH', name: 'Bosnia and Herzegovina', flag: '🇧🇦' },
  { code: 'BOT', name: 'Botswana', flag: '🇧🇼' },
  { code: 'BRA', name: 'Brazil', flag: '🇧🇷' },
  { code: 'BRU', name: 'Brunei', flag: '🇧🇳' },
  { code: 'BUL', name: 'Bulgaria', flag: '🇧🇬' },
  { code: 'BFA', name: 'Burkina Faso', flag: '🇧🇫' },
  { code: 'BDI', name: 'Burundi', flag: '🇧🇮' },
  { code: 'CPV', name: 'Cabo Verde', flag: '🇨🇻' },
  { code: 'CAM', name: 'Cambodia', flag: '🇰🇭' },
  { code: 'CMR', name: 'Cameroon', flag: '🇨🇲' },
  { code: 'CAN', name: 'Canada', flag: '🇨🇦' },
  { code: 'CAF', name: 'Central African Republic', flag: '🇨🇫' },
  { code: 'CHA', name: 'Chad', flag: '🇹🇩' },
  { code: 'CHI', name: 'Chile', flag: '🇨🇱' },
  { code: 'CHN', name: 'China', flag: '🇨🇳' },
  { code: 'COL', name: 'Colombia', flag: '🇨🇴' },
  { code: 'COM', name: 'Comoros', flag: '🇰🇲' },
  { code: 'CGO', name: 'Congo', flag: '🇨🇬' },
  { code: 'COD', name: 'DR Congo', flag: '🇨🇩' },
  { code: 'CRC', name: 'Costa Rica', flag: '🇨🇷' },
  { code: 'CRO', name: 'Croatia', flag: '🇭🇷' },
  { code: 'CUB', name: 'Cuba', flag: '🇨🇺' },
  { code: 'CYP', name: 'Cyprus', flag: '🇨🇾' },
  { code: 'CZE', name: 'Czech Republic', flag: '🇨🇿' },
  { code: 'DEN', name: 'Denmark', flag: '🇩🇰' },
  { code: 'DJI', name: 'Djibouti', flag: '🇩🇯' },
  { code: 'DMA', name: 'Dominica', flag: '🇩🇲' },
  { code: 'DOM', name: 'Dominican Republic', flag: '🇩🇴' },
  { code: 'ECU', name: 'Ecuador', flag: '🇪🇨' },
  { code: 'EGY', name: 'Egypt', flag: '🇪🇬' },
  { code: 'SLV', name: 'El Salvador', flag: '🇸🇻' },
  { code: 'ENG', name: 'England', flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿' },
  { code: 'EQG', name: 'Equatorial Guinea', flag: '🇬🇶' },
  { code: 'ERI', name: 'Eritrea', flag: '🇪🇷' },
  { code: 'EST', name: 'Estonia', flag: '🇪🇪' },
  { code: 'SWZ', name: 'Eswatini', flag: '🇸🇿' },
  { code: 'ETH', name: 'Ethiopia', flag: '🇪🇹' },
  { code: 'FRO', name: 'Faroe Islands', flag: '🇫🇴' },
  { code: 'FIJ', name: 'Fiji', flag: '🇫🇯' },
  { code: 'FIN', name: 'Finland', flag: '🇫🇮' },
  { code: 'FRA', name: 'France', flag: '🇫🇷' },
  { code: 'GAB', name: 'Gabon', flag: '🇬🇦' },
  { code: 'GAM', name: 'Gambia', flag: '🇬🇲' },
  { code: 'GEO', name: 'Georgia', flag: '🇬🇪' },
  { code: 'GER', name: 'Germany', flag: '🇩🇪' },
  { code: 'GHA', name: 'Ghana', flag: '🇬🇭' },
  { code: 'GIB', name: 'Gibraltar', flag: '🇬🇮' },
  { code: 'GRE', name: 'Greece', flag: '🇬🇷' },
  { code: 'GRL', name: 'Greenland', flag: '🇬🇱' },
  { code: 'GRN', name: 'Grenada', flag: '🇬🇩' },
  { code: 'GUA', name: 'Guatemala', flag: '🇬🇹' },
  { code: 'GUI', name: 'Guinea', flag: '🇬🇳' },
  { code: 'GNB', name: 'Guinea-Bissau', flag: '🇬🇼' },
  { code: 'GUY', name: 'Guyana', flag: '🇬🇾' },
  { code: 'HAI', name: 'Haiti', flag: '🇭🇹' },
  { code: 'HON', name: 'Honduras', flag: '🇭🇳' },
  { code: 'HKG', name: 'Hong Kong', flag: '🇭🇰' },
  { code: 'HUN', name: 'Hungary', flag: '🇭🇺' },
  { code: 'ISL', name: 'Iceland', flag: '🇮🇸' },
  { code: 'IND', name: 'India', flag: '🇮🇳' },
  { code: 'IDN', name: 'Indonesia', flag: '🇮🇩' },
  { code: 'IRN', name: 'Iran', flag: '🇮🇷' },
  { code: 'IRQ', name: 'Iraq', flag: '🇮🇶' },
  { code: 'IRL', name: 'Ireland', flag: '🇮🇪' },
  { code: 'ISR', name: 'Israel', flag: '🇮🇱' },
  { code: 'ITA', name: 'Italy', flag: '🇮🇹' },
  { code: 'CIV', name: 'Ivory Coast', flag: '🇨🇮' },
  { code: 'JAM', name: 'Jamaica', flag: '🇯🇲' },
  { code: 'JPN', name: 'Japan', flag: '🇯🇵' },
  { code: 'JOR', name: 'Jordan', flag: '🇯🇴' },
  { code: 'KAZ', name: 'Kazakhstan', flag: '🇰🇿' },
  { code: 'KEN', name: 'Kenya', flag: '🇰🇪' },
  { code: 'KOS', name: 'Kosovo', flag: '🇽🇰' },
  { code: 'KUW', name: 'Kuwait', flag: '🇰🇼' },
  { code: 'KGZ', name: 'Kyrgyzstan', flag: '🇰🇬' },
  { code: 'LAO', name: 'Laos', flag: '🇱🇦' },
  { code: 'LVA', name: 'Latvia', flag: '🇱🇻' },
  { code: 'LBN', name: 'Lebanon', flag: '🇱🇧' },
  { code: 'LES', name: 'Lesotho', flag: '🇱🇸' },
  { code: 'LBR', name: 'Liberia', flag: '🇱🇷' },
  { code: 'LBY', name: 'Libya', flag: '🇱🇾' },
  { code: 'LIE', name: 'Liechtenstein', flag: '🇱🇮' },
  { code: 'LTU', name: 'Lithuania', flag: '🇱🇹' },
  { code: 'LUX', name: 'Luxembourg', flag: '🇱🇺' },
  { code: 'MAD', name: 'Madagascar', flag: '🇲🇬' },
  { code: 'MWI', name: 'Malawi', flag: '🇲🇼' },
  { code: 'MAS', name: 'Malaysia', flag: '🇲🇾' },
  { code: 'MDV', name: 'Maldives', flag: '🇲🇻' },
  { code: 'MLI', name: 'Mali', flag: '🇲🇱' },
  { code: 'MLT', name: 'Malta', flag: '🇲🇹' },
  { code: 'MTN', name: 'Mauritania', flag: '🇲🇷' },
  { code: 'MRI', name: 'Mauritius', flag: '🇲🇺' },
  { code: 'MEX', name: 'Mexico', flag: '🇲🇽' },
  { code: 'MDA', name: 'Moldova', flag: '🇲🇩' },
  { code: 'MCO', name: 'Monaco', flag: '🇲🇨' },
  { code: 'MNG', name: 'Mongolia', flag: '🇲🇳' },
  { code: 'MNE', name: 'Montenegro', flag: '🇲🇪' },
  { code: 'MAR', name: 'Morocco', flag: '🇲🇦' },
  { code: 'MOZ', name: 'Mozambique', flag: '🇲🇿' },
  { code: 'MYA', name: 'Myanmar', flag: '🇲🇲' },
  { code: 'NAM', name: 'Namibia', flag: '🇳🇦' },
  { code: 'NEP', name: 'Nepal', flag: '🇳🇵' },
  { code: 'NED', name: 'Netherlands', flag: '🇳🇱' },
  { code: 'NZL', name: 'New Zealand', flag: '🇳🇿' },
  { code: 'NCA', name: 'Nicaragua', flag: '🇳🇮' },
  { code: 'NIG', name: 'Niger', flag: '🇳🇪' },
  { code: 'NGA', name: 'Nigeria', flag: '🇳🇬' },
  { code: 'MKD', name: 'North Macedonia', flag: '🇲🇰' },
  { code: 'NIR', name: 'Northern Ireland', flag: '🇬🇧' },
  { code: 'NOR', name: 'Norway', flag: '🇳🇴' },
  { code: 'OMA', name: 'Oman', flag: '🇴🇲' },
  { code: 'PAK', name: 'Pakistan', flag: '🇵🇰' },
  { code: 'PLE', name: 'Palestine', flag: '🇵🇸' },
  { code: 'PAN', name: 'Panama', flag: '🇵🇦' },
  { code: 'PNG', name: 'Papua New Guinea', flag: '🇵🇬' },
  { code: 'PAR', name: 'Paraguay', flag: '🇵🇾' },
  { code: 'PER', name: 'Peru', flag: '🇵🇪' },
  { code: 'PHI', name: 'Philippines', flag: '🇵🇭' },
  { code: 'POL', name: 'Poland', flag: '🇵🇱' },
  { code: 'POR', name: 'Portugal', flag: '🇵🇹' },
  { code: 'QAT', name: 'Qatar', flag: '🇶🇦' },
  { code: 'ROU', name: 'Romania', flag: '🇷🇴' },
  { code: 'RUS', name: 'Russia', flag: '🇷🇺' },
  { code: 'RWA', name: 'Rwanda', flag: '🇷🇼' },
  { code: 'SAM', name: 'Samoa', flag: '🇼🇸' },
  { code: 'SMR', name: 'San Marino', flag: '🇸🇲' },
  { code: 'KSA', name: 'Saudi Arabia', flag: '🇸🇦' },
  { code: 'SCO', name: 'Scotland', flag: '🏴󠁧󠁢󠁳󠁣󠁴󠁿' },
  { code: 'SEN', name: 'Senegal', flag: '🇸🇳' },
  { code: 'SRB', name: 'Serbia', flag: '🇷🇸' },
  { code: 'SLE', name: 'Sierra Leone', flag: '🇸🇱' },
  { code: 'SGP', name: 'Singapore', flag: '🇸🇬' },
  { code: 'SVK', name: 'Slovakia', flag: '🇸🇰' },
  { code: 'SVN', name: 'Slovenia', flag: '🇸🇮' },
  { code: 'SOM', name: 'Somalia', flag: '🇸🇴' },
  { code: 'RSA', name: 'South Africa', flag: '🇿🇦' },
  { code: 'KOR', name: 'South Korea', flag: '🇰🇷' },
  { code: 'SSD', name: 'South Sudan', flag: '🇸🇸' },
  { code: 'ESP', name: 'Spain', flag: '🇪🇸' },
  { code: 'SRI', name: 'Sri Lanka', flag: '🇱🇰' },
  { code: 'SUD', name: 'Sudan', flag: '🇸🇩' },
  { code: 'SUR', name: 'Suriname', flag: '🇸🇷' },
  { code: 'SWE', name: 'Sweden', flag: '🇸🇪' },
  { code: 'SUI', name: 'Switzerland', flag: '🇨🇭' },
  { code: 'SYR', name: 'Syria', flag: '🇸🇾' },
  { code: 'TPE', name: 'Taiwan', flag: '🇹🇼' },
  { code: 'TJK', name: 'Tajikistan', flag: '🇹🇯' },
  { code: 'TAN', name: 'Tanzania', flag: '🇹🇿' },
  { code: 'THA', name: 'Thailand', flag: '🇹🇭' },
  { code: 'TOG', name: 'Togo', flag: '🇹🇬' },
  { code: 'TRI', name: 'Trinidad and Tobago', flag: '🇹🇹' },
  { code: 'TUN', name: 'Tunisia', flag: '🇹🇳' },
  { code: 'TUR', name: 'Turkey', flag: '🇹🇷' },
  { code: 'TKM', name: 'Turkmenistan', flag: '🇹🇲' },
  { code: 'UGA', name: 'Uganda', flag: '🇺🇬' },
  { code: 'UKR', name: 'Ukraine', flag: '🇺🇦' },
  { code: 'UAE', name: 'United Arab Emirates', flag: '🇦🇪' },
  { code: 'USA', name: 'United States', flag: '🇺🇸' },
  { code: 'URU', name: 'Uruguay', flag: '🇺🇾' },
  { code: 'UZB', name: 'Uzbekistan', flag: '🇺🇿' },
  { code: 'VEN', name: 'Venezuela', flag: '🇻🇪' },
  { code: 'VIE', name: 'Vietnam', flag: '🇻🇳' },
  { code: 'WAL', name: 'Wales', flag: '🏴󠁧󠁢󠁷󠁬󠁳󠁿' },
  { code: 'YEM', name: 'Yemen', flag: '🇾🇪' },
  { code: 'ZAM', name: 'Zambia', flag: '🇿🇲' },
  { code: 'ZIM', name: 'Zimbabwe', flag: '🇿🇼' }
];

// Sort alphabetically by Country Name
COUNTRIES.sort((a, b) => a.name.localeCompare(b.name));

// Fast lookup map by code and name
const COUNTRY_MAP = {};
COUNTRIES.forEach(c => {
  COUNTRY_MAP[c.code.toUpperCase()] = c;
  COUNTRY_MAP[c.name.toUpperCase()] = c;
});

// Helper to look up country details
export function getCountryFlag(codeOrName) {
  if (!codeOrName) return { code: 'ENG', name: 'England', flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿' };
  const key = String(codeOrName).toUpperCase().trim();
  return COUNTRY_MAP[key] || { code: key, name: key, flag: '🌐' };
}

// Helper to generate <option> tags sorted A-Z
export function renderCountryOptions(selectedCode = 'ENG') {
  const normSelected = String(selectedCode).toUpperCase().trim();
  return COUNTRIES.map(c => `
    <option value="${c.code}" ${c.code === normSelected ? 'selected' : ''}>
      ${c.flag} ${c.name} (${c.code})
    </option>
  `).join('');
}
